<?php /*~~~*/
//Set this to 1 if you need to edit the fields
$dev = false;

if (
	(
		$dev == false &&
		lct_is_wpall() == false
	) ||
	$dev == 'force_local'
):

	acf_add_local_field_group( [
		'key'                   => 'group_55b007453cd60',
		'title'                 => 'General Settings',      //TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE
		'fields'                => [
			[
				'key'               => 'field_56f309aa4aa1d',
				'label'             => 'This Site',
				'name'              => '_copy',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
			],
			[
				'key'               => 'field_56f309bb4aa1e',
				'label'             => 'Location Directions URL',
				'name'              => 'lct:::get_directions',
				'type'              => 'url',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => '',
			],
			[
				'key'               => 'field_56df4a8ab6b2f',
				'label'             => 'General',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
			],
			[
				'key'               => 'field_55ce8ec44d416',
				'label'             => 'We have some CSS tweaks that come in real handy. But they may interfere with your theme. Just disable this if they do.',
				'name'              => 'lct:::enable_front_css',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'           => 'Enable LCT\'s front.css',
				'default_value'     => 1,
			],
			[
				'key'               => 'field_56e1137a096f9',
				'label'             => 'Hide Yoast SEO OG Site Name',
				'name'              => 'lct:::hide_og_site_name',
				'type'              => 'true_false',
				'instructions'      => 'Sometimes you may not want the OG site_name tag in your html.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'           => 'Hide OG Site Name',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_56e8ac20d3372',
				'label'             => 'Page Notes Support',
				'name'              => 'lct:::use_page_note',
				'type'              => 'true_false',
				'instructions'      => 'You can add internal notes to pages. Good for reminders and stuff like that.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'           => 'Use Page Notes',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55b27e8dd2719',
				'label'             => 'Hide the admin bar on the front-end: For all...',
				'name'              => 'lct:::hide_admin_bar__by_role',
				'type'              => 'checkbox',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'           => [
					'administrator' => 'Administrator',
					'editor'        => 'Editor',
					'author'        => 'Author',
					'contributor'   => 'Contributor',
					'subscriber'    => 'Subscriber',
				],
				'default_value'     => [
					0 => 'contributor',
					1 => 'subscriber',
					2 => 'customer',
				],
				'layout'            => 'vertical',
				'toggle'            => 1,
			],
			[
				'key'               => 'field_56e12ed3c33d1',
				'label'             => 'Choose how you would like WP to handle the [raw] tags',
				'name'              => 'lct:::choose_a_raw_tag_option',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'           => [
					'wpautop' => 'Use the default Wordpress wpautop',
					'off'     => 'Off: turn wpautop off sitewide',
					'old'     => 'Old: [raw] tag only works once',
					'new'     => '[raw] tags work multi time and only on content contained in tags',
				],
				'default_value'     => [
					0 => 'new',
				],
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'placeholder'       => '',
				'disabled'          => 0,
				'readonly'          => 0,
			],
			[
				'key'               => 'field_56df4a68b6b2e',
				'label'             => 'Profile Page',
				'name'              => 'profile_page',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
			],
			[
				'key'               => 'field_56df4a4eb6b2d',
				'label'             => 'Hide WooCommerce items on profile page',
				'name'              => 'lct:::hide_woocommerce_items_on_profile_page',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Hide WooCommerce items on profile page',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_56df4a95b6b30',
				'label'             => 'Hide Color Picker on profile page',
				'name'              => 'lct:::hide_color_picker_on_profile_page',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Hide Color Picker on profile page',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_56df4a97b6b31',
				'label'             => 'Hide Contact Methods on profile page',
				'name'              => 'lct:::hide_contact_methods_on_profile_page',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Hide Contact Methods on profile page',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_56ec459803826',
				'label'             => 'Random Schtuff',
				'name'              => '_copy',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
			],
			[
				'key'               => 'field_56e0f5ee3e161',
				'label'             => 'Print User Agent In Footer',
				'name'              => 'lct:::print_user_agent_in_footer',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Print User Agent In Footer',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55cea16b5cc0f',
				'label'             => 'Disable Auto Set User Timezone',
				'name'              => 'lct:::disable_auto_set_user_timezone',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Disable Auto Set User Timezone',
				'default_value'     => 1,
			],
			[
				'key'               => 'field_5717d0ee1a10e',
				'label'             => 'Loadable Google Fonts',
				'name'              => 'lct:::load_google_fonts',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'table',
				'button_label'      => 'Add Google Font',
				'sub_fields'        => [
					[
						'key'               => 'field_5717d1071a10f',
						'label'             => 'Name',
						'name'              => 'name',
						'type'              => 'text',
						'instructions'      => 'Case Sensitive',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => 30,
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					],
					[
						'key'               => 'field_5717d11a1a110',
						'label'             => 'Additional Settings',
						'name'              => 'additional',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => 50,
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					],
					[
						'key'               => 'field_5717d1c53541f',
						'label'             => 'Always Load',
						'name'              => 'always_load',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => 20,
							'class' => 'hide_label',
							'id'    => '',
						],
						'message'           => 'Always Load',
						'default_value'     => 1,
					],
				],
			],
			[
				'key'               => 'field_5727c896bf375',
				'label'             => 'Loadable Adobe Typekits',
				'name'              => 'lct:::load_typekit',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'collapsed'         => '',
				'min'               => '',
				'max'               => '',
				'layout'            => 'table',
				'button_label'      => 'Add Adobe Typekit',
				'sub_fields'        => [
					[
						'key'               => 'field_5727c896bf376',
						'label'             => 'Name',
						'name'              => 'name',
						'type'              => 'text',
						'instructions'      => 'Case Sensitive',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => 30,
							'class' => '',
							'id'    => '',
						],
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
						'readonly'          => 0,
						'disabled'          => 0,
					],
					[
						'key'               => 'field_5727c896bf378',
						'label'             => 'Always Load',
						'name'              => 'always_load',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => [
							'width' => 20,
							'class' => 'hide_label',
							'id'    => '',
						],
						'message'           => 'Always Load',
						'default_value'     => 1,
					],
				],
			],
			[
				'key'               => 'field_56dfafeaf6ba3',
				'label'             => 'Google Map API',
				'name'              => 'lct:::google_map_api',
				'type'              => 'text',
				'instructions'      => 'Required if your custom code is calling any of the lct_geocode() functions.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
			[
				'key'               => 'field_5717d256b1853',
				'label'             => 'Deprecated',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
			],
			[
				'key'               => 'field_56e12ea4c33d0',
				'label'             => 'Default Taxonomy',
				'name'              => 'lct:::default_taxonomy',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'choices'           => [
					'category'              => 'category',
					'faq_category'          => 'faq_category',
					'link_category'         => 'link_category',
					'nav_menu'              => 'nav_menu',
					'portfolio_category'    => 'portfolio_category',
					'portfolio_skills'      => 'portfolio_skills',
					'portfolio_tags'        => 'portfolio_tags',
					'post_format'           => 'post_format',
					'post_tag'              => 'post_tag',
					'slide-page'            => 'slide-page',
					'themefusion_es_groups' => 'themefusion_es_groups',
				],
				'default_value'     => [
				],
				'allow_null'        => 1,
				'multiple'          => 0,
				'ui'                => 1,
				'ajax'              => 0,
				'placeholder'       => '',
				'disabled'          => 0,
				'readonly'          => 0,
			],
		],
		'location'              => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_settings',
				],
			],
		],
		'menu_order'            => 1,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	] );


	if ( class_exists( 'GFForms' ) ) {
		acf_add_local_field_group( [
			'key'                   => 'group_55ce86abcd40a',
			'title'                 => 'Gravity Forms',      //TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE
			'fields'                => [
				[
					'key'               => 'field_55cea24748247',
					'label'             => 'Use LCT\'s Gravity Forms CSS Tweaks',
					'name'              => 'lct:::use_gforms_css_tweaks',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Use LCT\'s Gravity Forms CSS Tweaks',
					'default_value'     => 1,
				],
				[
					'key'               => 'field_55ce86bd562d8',
					'label'             => 'Custom Submit Button Class',
					'name'              => 'lct:::gform_button_custom_class',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_55cea24748247',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				],
				[
					'key'               => 'field_56e1220e69af1',
					'label'             => 'Enable Cj Spam Check',
					'name'              => 'lct:::enable_cj_spam_check',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Enable Cj Spam Check',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_56e1221169af2',
					'label'             => 'Enable Cj Spam Check Email',
					'name'              => 'lct:::enable_cj_spam_check_email',
					'type'              => 'email',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_56e1220e69af1',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'               => 'field_56e1250c3ef86',
					'label'             => 'Store Form Data',
					'name'              => 'lct:::gforms_store',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'choices'           => [
						0 => 'Don\'t store the selected forms',
						1 => 'Yes, store the selected forms',
					],
					'other_choice'      => 0,
					'save_other_choice' => 0,
					'default_value'     => 0,
					'layout'            => 'vertical',
				],
				[
					'key'               => 'field_56e125133ef87',
					'label'             => 'Select Gravity Forms',
					'name'              => 'lct:::gforms',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'choices'           => [
						52 => 'Contact',
						53 => 'Contact - Home',
						51 => 'Sidebar Contact',
					],
					'default_value'     => [
					],
					'layout'            => 'vertical',
					'toggle'            => 0,
				],
			],
			'location'              => [
				[
					[
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'lct_acf_op_main_settings',
					],
				],
			],
			'menu_order'            => 2,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		] );
	}


	if ( $this->Avada ) {
		acf_add_local_field_group( [
			'key'                   => 'group_55b94b2bcdb25',
			'title'                 => 'Theme Settings: Avada',      //TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE
			'fields'                => [
				[
					'key'               => 'field_55ce9ee4e2e26',
					'label'             => 'Disable LCT\'s Avada.css',
					'name'              => 'lct:::disable_avada_css',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Disable LCT\'s Avada.css',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_5716edeac6790',
					'label'             => 'Disable LCT\'s Avada-page_defaults.css',
					'name'              => 'lct:::enable_avada_css_page_defaults',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Disable LCT\'s Avada-page_defaults.css',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_5716f281ee4e8',
					'label'             => 'Set Page Title Bar height to auto',
					'name'              => 'lct:::page_title_bar_auto',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Set Page Title Bar height to auto',
					'default_value'     => 1,
				],
				[
					'key'               => 'field_5716f2dbee4e9',
					'label'             => 'Page Title Bar Top Padding',
					'name'              => 'lct:::page_title_bar_padding_top',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_5716f281ee4e8',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => 10,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => 4,
					'readonly'          => 0,
					'disabled'          => 0,
				],
				[
					'key'               => 'field_5716f307ee4ea',
					'label'             => 'Page Title Bar Bottom Padding',
					'name'              => 'lct:::page_title_bar_padding_bottom',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_5716f281ee4e8',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => 10,
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => 4,
					'readonly'          => 0,
					'disabled'          => 0,
				],
				[
					'key'               => 'field_56e9da87e4d78',
					'label'             => 'Disable Image Sizes',
					'name'              => 'lct:::disable_image_sizes',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'choices'           => [
						'blog-large'             => 'blog-large',
						'blog-medium'            => 'blog-medium',
						'tabs-img'               => 'tabs-img',
						'related-img'            => 'related-img',
						'portfolio-full'         => 'portfolio-full',
						'portfolio-one'          => 'portfolio-one',
						'portfolio-two'          => 'portfolio-two',
						'portfolio-three'        => 'portfolio-three',
						'portfolio-four'         => 'portfolio-four',
						'portfolio-five'         => 'portfolio-five',
						'portfolio-six'          => 'portfolio-six',
						'recent-posts'           => 'recent-posts',
						'recent-works-thumbnail' => 'recent-works-thumbnail',
					],
					'default_value'     => [
						0  => 'blog-large',
						1  => 'tabs-img',
						2  => 'related-img',
						3  => 'portfolio-full',
						4  => 'portfolio-one',
						5  => 'portfolio-two',
						6  => 'portfolio-three',
						7  => 'portfolio-four',
						8  => 'portfolio-five',
						9  => 'portfolio-six',
						10 => 'recent-works-thumbnail',
					],
					'allow_null'        => 1,
					'multiple'          => 1,
					'ui'                => 1,
					'ajax'              => 0,
					'placeholder'       => '',
					'disabled'          => 0,
					'readonly'          => 0,
				],
				[
					'key'               => 'field_56e1f527a2803',
					'label'             => 'Custom Post Excerpt Read More Replacement',
					'name'              => 'lct:::avada::is_post_excerpt_read_more',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Custom Post Excerpt Read More Replacement',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_55b94b4f5caa0',
					'label'             => 'Post Excerpt Read More Replacement',
					'name'              => 'lct:::avada::post_excerpt_read_more',
					'type'              => 'textarea',
					'instructions'      => 'Replace [...] with what ever you want.',
					'required'          => 0,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_56e1f527a2803',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => 'br',
					'readonly'          => 0,
					'disabled'          => 0,
				],
				[
					'key'               => 'field_56d745ecb3f8d',
					'label'             => 'Show Sandbox Warning',
					'name'              => 'lct:::show_sandbox_warning',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => 25,
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Show Sandbox Warning',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_56d74658b3f8e',
					'label'             => 'For Dev',
					'name'              => 'lct:::show_sandbox_warning_dev',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_56d745ecb3f8d',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => 25,
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'For Dev',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_56d74678b3f8f',
					'label'             => 'For Sandbox',
					'name'              => 'lct:::show_sandbox_warning_sandbox',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_56d745ecb3f8d',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => 25,
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'For Sandbox',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_56d74c81337e3',
					'label'             => 'Show Sandbox Warning on the Side',
					'name'              => 'lct:::show_sandbox_warning_side',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_56d745ecb3f8d',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => 25,
						'class' => 'hide_label',
						'id'    => '',
					],
					'message'           => 'Show Sandbox Warning on the Side',
					'default_value'     => 0,
				],
				[
					'key'               => 'field_56d74e3410bd1',
					'label'             => 'Live URL',
					'name'              => 'lct:::show_sandbox_warning_url',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => [
						[
							[
								'field'    => 'field_56d745ecb3f8d',
								'operator' => '==',
								'value'    => '1',
							],
						],
					],
					'wrapper'           => [
						'width' => 100,
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'placeholder'       => '',
				],
			],
			'location'              => [
				[
					[
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'lct_acf_op_main_settings',
					],
				],
			],
			'menu_order'            => 3,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		] );
	}


	acf_add_local_field_group( [
		'key'                   => 'group_55b7ee000c834',
		'title'                 => 'Shortcodes',      //TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE----TITLE
		'fields'                => [
			[
				'key'               => 'field_55b7ee96f830d',
				'label'             => 'Copyright',
				'name'              => 'copyright',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'placement'         => 'top',
				'endpoint'          => 0,
			],
			[
				'key'               => 'field_55b7eea6f830e',
				'label'             => 'Copyright Shortcode Instructions',
				'name'              => 'footer_copyright_shortcode_instructions',
				'type'              => 'message',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'           => 'Place this shortcode where you want the copyright text to go: <strong>&#91;lct_copyright&#93;</strong>',
				'new_lines'         => 'wpautop',
				'esc_html'          => 0,
			],
			[
				'key'               => 'field_55b7f1dfd8450',
				'label'             => 'I want to use this shortcode',
				'name'              => 'lct:::sc::use_this_shortcode',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => [
					'width' => '',
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'I want to use this shortcode',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55b7f2ed35d96',
				'label'             => 'Title',
				'name'              => 'lct:::sc::title',
				'type'              => 'text',
				'instructions'      => 'usually the company name.',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => 75,
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => 'Company ABC, Inc.',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
			[
				'key'               => 'field_55b7f4214369d',
				'label'             => 'Link the Title',
				'name'              => 'lct:::sc::link_title',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => 25,
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Link the Title',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55b7f4504369e',
				'label'             => 'Title Link',
				'name'              => 'lct:::sc::title_link',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
						[
							'field'    => 'field_55b7f4214369d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => 50,
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => 'default is: /',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
			[
				'key'               => 'field_55b806ddcad96',
				'label'             => 'Open in New Tab',
				'name'              => 'lct:::sc::title_link_blank',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
						[
							'field'    => 'field_55b7f4214369d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => 25,
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Open in New Tab',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55b80590aa4c1',
				'label'             => 'Disable Link on Posts',
				'name'              => 'lct:::sc::no_single_link',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
						[
							'field'    => 'field_55b7f4214369d',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => 25,
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'Disable Link on Posts',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55b7f33935d98',
				'label'             => 'Builder Plug',
				'name'              => 'lct:::sc::builder_plug',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '',
				'placeholder'       => 'Web Designs, Inc.',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
			[
				'key'               => 'field_55b7f33835d97',
				'label'             => 'XML Sitemap URL',
				'name'              => 'lct:::sc::xml',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => '/sitemap_index.xml',
				'placeholder'       => '/sitemap_index.xml',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
			[
				'key'               => 'field_56ec4e3e1bebc',
				'label'             => 'Privacy Policy Page',
				'name'              => 'lct:::sc::privacy_policy_page',
				'type'              => 'post_object',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'post_type'         => [
					0 => 'page',
				],
				'taxonomy'          => [
				],
				'allow_null'        => 1,
				'multiple'          => 0,
				'return_format'     => 'object',
				'ui'                => 1,
			],
			[
				'key'               => 'field_56ec4de712b52',
				'label'             => 'Copyright Layout Template',
				'name'              => '',
				'type'              => 'message',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'message'           => '<strong>Layout Variables:</strong>
										<ul>
										<li>{copy_symbol} = &copy;</li>
										<li>{year} = the current year</li>
										<li>{title} = the title field entered above</li>
										<li>{builder_plug} = the builder_plug entered above</li>
										<li>{XML_sitemap} = link to the above sitemap URL</li>
										<li>{privacy} = link to the above privacy policy page</li>
										</ul>
										
										Let me know if you need other variables and I can add them for you.',
				'new_lines'         => 'wpautop',
				'esc_html'          => 0,
			],
			[
				'key'               => 'field_55b7f04b5c23b',
				'label'             => 'Layout',
				'name'              => 'lct:::sc::copyright_layout',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
						[
							'field'    => 'field_55ee5056814a2',
							'operator' => '!=',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => 'Copyright {copy_symbol} {year} {title} | {builder_plug} | {XML_sitemap}',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
			[
				'key'               => 'field_55ee5056814a2',
				'label'             => 'Multi-Line Layout',
				'name'              => 'lct:::sc::use_copyright_layout_multi',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => 25,
					'class' => 'hide_label',
					'id'    => '',
				],
				'message'           => 'I want to use a multi-line layout',
				'default_value'     => 0,
			],
			[
				'key'               => 'field_55ee504e814a1',
				'label'             => 'Multi-Line Layout',
				'name'              => 'lct:::sc::copyright_layout_multi',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => [
					[
						[
							'field'    => 'field_55b7f1dfd8450',
							'operator' => '==',
							'value'    => '1',
						],
						[
							'field'    => 'field_55ee5056814a2',
							'operator' => '==',
							'value'    => '1',
						],
					],
				],
				'wrapper'           => [
					'width' => '',
					'class' => '',
					'id'    => '',
				],
				'default_value'     => 'Copyright {copy_symbol} {year} {title} | {builder_plug} | {XML_sitemap}',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => '',
				'new_lines'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			],
		],
		'location'              => [
			[
				[
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'lct_acf_op_main_settings',
				],
			],
		],
		'menu_order'            => 4,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	] );

endif;
